version: '3'
services:
  front:
    image: nginx:latest
    container_name: front
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt/live
      - ./key:/etc/letsencrypt/live
    depends_on:
      - drupal
    networks:
      - front


  drupal:
    image: drupal:latest
    container_name: drupal 
    volumes:
      - drupal:/var/www/html
    networks:
      - front
      - back
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: database
    networks:
      - back
    env_file:
      - ./back/env_variable.env 
    volumes:
      - database:/var/lib/mysql

networks:
  back:
  front:

volumes:
  database:
  drupal:
  certbot-etc:


